# version: '3.4'

services:
  services.Api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80       
      - ServiceName=Mail Solution API
      - MailSetting__Mail=ittranhai@gmail.com
      - MailSetting__DisplayName=Mail Solution
      - MailSetting__Password=sqxljnxmidrvpelk
      - MailSetting__Host=smtp.gmail.com
      - MailSetting__Port=587
    ports:
      - "8000:80"
  services.App:
    ports:
      - "4300:80" 
    volumes:
      - ./env/app.config.json:/usr/share/nginx/html/assets/config.json:ro