# version: '3.4'

services:
  services.Api:
    environment: # khi enviroment thay đổi và chạy lệnh docker compose up thì sẽ restart container
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80       
      # - ServiceName=AAA Mail Solution API
      # - MailSetting__Mail=ittranhai@gmail.com
      # - MailSetting__DisplayName=Mail Solution
      # - MailSetting__Password=sqxljnxmidrvpelk
      # - MailSetting__Host=smtp.gmail.com
      # - MailSetting__Port=587
    ports:
      - "8000:80"
    volumes: # khi volumes thay đổi (chạy lệnh docker compose up không tác dụng) cần chạy docker compose restart services.Api
      - ./AppSettings/api.appsettings.json:/app/appsettings.json
  services.App:
    ports:
      - "4300:80" 
    volumes:
      - ./AppSettings/app.appsettings.json:/usr/share/nginx/html/assets/appsettings.json:ro