# version: '3.4'

services:
  services.Api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8000:80"
    volumes:
      - ./AppSettings/api.appsettings.json:/app/appsettings.json:ro
  services.App:
    ports:
      - "4300:80" 
    volumes:
      - ./AppSettings/app.appsettings.json:/usr/share/nginx/html/assets/appsettings.json:ro